# Generated by Django 4.2.30 on 2026-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SongProfileApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="senha",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
