# Generated by Django 4.2.30 on 2026-04-21 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SongProfileApp", "0002_user_senha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.CharField(blank=True, max_length=30, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Prefiro não dizer"),
                ],
                max_length=1,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="lastName",
            field=models.CharField(blank=True, max_length=30, verbose_name="Sobrenome"),
        ),
        migrations.CreateModel(
            name="SongList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "song1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songlist_1",
                        to="SongProfileApp.song",
                    ),
                ),
                (
                    "song2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songlist_2",
                        to="SongProfileApp.song",
                    ),
                ),
                (
                    "song3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songlist_3",
                        to="SongProfileApp.song",
                    ),
                ),
                (
                    "song4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songlist_4",
                        to="SongProfileApp.song",
                    ),
                ),
                (
                    "song5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songlist_5",
                        to="SongProfileApp.song",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songlist",
                        to="SongProfileApp.user",
                    ),
                ),
            ],
        ),
    ]
